services:
    david63.statsonindex.listener:
        class: david63\statsonindex\event\listener
        arguments:
            - @config
            - @template
            - @user
        tags:
            - { name: event.listener }
